//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmuLoader.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceCore {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCore() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmuLoader.Core.Properties.ResourceCore", typeof(ResourceCore).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;menu&gt;
        ///	&lt;header&gt;
        ///		&lt;listname&gt;MAME&lt;/listname&gt;
        ///		&lt;lastlistupdate&gt;02/08/2016&lt;/lastlistupdate&gt;
        ///		&lt;listversion&gt;.160 Ongoing&lt;/listversion&gt;
        ///		&lt;exporterversion&gt;HyperList XML Exporter Version 1.3 Copywrite (c) 2009-2011 William Strong&lt;/exporterversion&gt;
        ///	&lt;/header&gt;
        ///	&lt;game name=&quot;88games&quot; index=&quot;true&quot; image=&quot;&apos;&quot;&gt;
        ///		&lt;description&gt;&amp;apos;88 Games&lt;/description&gt;
        ///		&lt;cloneof&gt;&lt;/cloneof&gt;
        ///		&lt;crc&gt;&lt;/crc&gt;
        ///		&lt;manufacturer&gt;Konami&lt;/manufacturer&gt;
        ///		&lt;year&gt;1988&lt;/year&gt;
        ///		&lt;genre&gt;Sports / Track &amp;amp; Field&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MAME {
            get {
                return ResourceManager.GetString("MAME", resourceCulture);
            }
        }
    }
}
